/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Principal;

import java.awt.CardLayout;
import javax.swing.UIManager;

/**
 *
 * @author Dulanjaya Tennekoon
 */
public class PrincipalWindow extends javax.swing.JFrame {
    private CardLayout layCard = new CardLayout();
    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow() {
        initComponents();
        startUpSettings();
    }
    
    public void startUpSettings() {
        setCardLayout();
        frameSettings();
    }
    
    public void frameSettings() {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("NTS Kurunegala");
    }
    
    public void setCardLayout() {
        pnlsubMain.setLayout(layCard);
        pnlsubMain.add("pnlStuInfo", pnlStuInfo);
        pnlsubMain.add("pnlLectInfo", pnlLectInfo);
        pnlsubMain.add("pnlRepeatWarnings", pnlRepeatWarnings);
        pnlsubMain.add("pnlSubjectInfo", pnlSubjectInformation);
        pnlsubMain.add("pnlODA",pnlOverallDailyAttendance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlSideBar = new javax.swing.JPanel();
        pnlControl = new javax.swing.JPanel();
        btnStuInfo = new javax.swing.JButton();
        btnLectInfo = new javax.swing.JButton();
        btnRepeatWarn = new javax.swing.JButton();
        btnSubjInfo = new javax.swing.JButton();
        btnOverallDailyAttendance = new javax.swing.JButton();
        lblPrincipal = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnUpdateRepWar = new javax.swing.JButton();
        lblLastchk = new javax.swing.JLabel();
        lblLastChkDate = new javax.swing.JLabel();
        pnlsubMain = new javax.swing.JPanel();
        pnlStuInfo = new javax.swing.JPanel();
        pnlStuPersonalInfo = new javax.swing.JPanel();
        lblStuInfoHeading = new javax.swing.JLabel();
        lblStuID = new javax.swing.JLabel();
        txtStuID = new javax.swing.JTextField();
        lblStuName = new javax.swing.JLabel();
        txtStuName = new javax.swing.JTextField();
        lblBatch = new javax.swing.JLabel();
        txtBatch = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        jspAddress = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblIDNo = new javax.swing.JLabel();
        tctIDno = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblDOReg = new javax.swing.JLabel();
        txtDOReg = new javax.swing.JTextField();
        canvasProfImage = new java.awt.Canvas();
        lblGuardName = new javax.swing.JLabel();
        txtGuardName = new javax.swing.JTextField();
        lblGuardPhone = new javax.swing.JLabel();
        txtGuardPhone = new javax.swing.JTextField();
        lblHostel = new javax.swing.JLabel();
        chkHostel = new javax.swing.JCheckBox();
        pnlStudSpecial = new javax.swing.JPanel();
        pnlStudSpeInfo = new javax.swing.JPanel();
        btnDailyAttendance = new javax.swing.JButton();
        btnSubAttendance = new javax.swing.JButton();
        btnSubMarks = new javax.swing.JButton();
        btnPrintCV = new javax.swing.JButton();
        lblCurricular = new javax.swing.JLabel();
        pnlStuDbControls = new javax.swing.JPanel();
        btnPrevRecord = new javax.swing.JButton();
        btnNextRecord = new javax.swing.JButton();
        lblStuDbControls = new javax.swing.JLabel();
        btnEditInfo = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        pnlStudSearch = new javax.swing.JPanel();
        lblSearchStudent = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        lblStudentID = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        btnSearchbyID = new javax.swing.JButton();
        btnSearchbyName = new javax.swing.JButton();
        pnlLectInfo = new javax.swing.JPanel();
        pnlsubLecturerInfo = new javax.swing.JPanel();
        lblLecturerInfo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLecturerID = new javax.swing.JLabel();
        lblLecturerName = new javax.swing.JLabel();
        lblNIC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        canvas1 = new java.awt.Canvas();
        jPanel5 = new javax.swing.JPanel();
        pnlStuDbControls1 = new javax.swing.JPanel();
        btnPrevRecord1 = new javax.swing.JButton();
        btnNextRecord1 = new javax.swing.JButton();
        lblStuDbControls1 = new javax.swing.JLabel();
        btnEditInfo1 = new javax.swing.JButton();
        btnDeleteRecord1 = new javax.swing.JButton();
        pnlRepeatWarnings = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlSubjectInformation = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNoOFLectures = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbLecturers = new javax.swing.JComboBox();
        cmbSubject = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmbLevel = new javax.swing.JComboBox();
        pnlOverallDailyAttendance = new javax.swing.JPanel();
        pnlsubOverallDailyAttendance = new javax.swing.JPanel();
        lbldate = new javax.swing.JLabel();
        cmbyear = new javax.swing.JComboBox();
        cmbMonth = new javax.swing.JComboBox();
        cmbDay = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbldate1 = new javax.swing.JLabel();
        cmbyear1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlSideBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlControl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnStuInfo.setText("Student Information");
        btnStuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuInfoActionPerformed(evt);
            }
        });

        btnLectInfo.setText("Lecturer Information");
        btnLectInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLectInfoActionPerformed(evt);
            }
        });

        btnRepeatWarn.setText("Repeat Warnings");
        btnRepeatWarn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepeatWarnActionPerformed(evt);
            }
        });

        btnSubjInfo.setText("Subject Information");
        btnSubjInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjInfoActionPerformed(evt);
            }
        });

        btnOverallDailyAttendance.setText("Overall Daily Attendance");
        btnOverallDailyAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverallDailyAttendanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRepeatWarn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLectInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(btnStuInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubjInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOverallDailyAttendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLectInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRepeatWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubjInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOverallDailyAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblPrincipal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPrincipal.setText("Principal");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnUpdateRepWar.setText("Update Repeat Warnings");
        btnUpdateRepWar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRepWarActionPerformed(evt);
            }
        });

        lblLastchk.setText("Last Check On:");
        lblLastchk.setEnabled(false);

        lblLastChkDate.setText("1900.01.01");
        lblLastChkDate.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateRepWar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblLastchk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLastChkDate)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdateRepWar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastchk)
                    .addComponent(lblLastChkDate))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSideBarLayout = new javax.swing.GroupLayout(pnlSideBar);
        pnlSideBar.setLayout(pnlSideBarLayout);
        pnlSideBarLayout.setHorizontalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSideBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPrincipal)
                .addGap(56, 56, 56))
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSideBarLayout.setVerticalGroup(
            pnlSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideBarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlsubMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlsubMain.setLayout(new java.awt.CardLayout());

        pnlStuPersonalInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblStuInfoHeading.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblStuInfoHeading.setText("Student Information");

        lblStuID.setText("Student ID");

        lblStuName.setText("Student Name");

        lblBatch.setText("Batch");

        lblAddress.setText("Address");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jspAddress.setViewportView(txtAddress);

        lblIDNo.setText("NIC");

        lblPhone.setText("Phone Number");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        lblDOB.setText("Date of Birth");

        lblDOReg.setText("Registration Date");

        txtDOReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDORegActionPerformed(evt);
            }
        });

        canvasProfImage.setBackground(new java.awt.Color(153, 153, 255));

        lblGuardName.setText("Guardian's Name");

        txtGuardName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardNameActionPerformed(evt);
            }
        });

        lblGuardPhone.setText("Guardian's Phone");

        lblHostel.setText("Hostel Student");

        chkHostel.setText("I am a hostel Student");
        chkHostel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHostelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStuPersonalInfoLayout = new javax.swing.GroupLayout(pnlStuPersonalInfo);
        pnlStuPersonalInfo.setLayout(pnlStuPersonalInfoLayout);
        pnlStuPersonalInfoLayout.setHorizontalGroup(
            pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress)
                            .addComponent(lblPhone)
                            .addComponent(lblDOReg)
                            .addComponent(lblGuardName)
                            .addComponent(lblGuardPhone)
                            .addComponent(lblHostel))
                        .addGap(24, 24, 24)
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                                .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGuardName)
                                    .addComponent(txtPhone)
                                    .addComponent(txtDOReg)
                                    .addComponent(txtGuardPhone)
                                    .addComponent(tctIDno, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(168, 168, 168))
                            .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                                .addComponent(chkHostel)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDOB)
                            .addComponent(lblBatch)
                            .addComponent(lblStuName)
                            .addComponent(lblStuID)
                            .addComponent(lblIDNo))
                        .addGap(40, 40, 40)
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                                .addComponent(lblStuInfoHeading)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                                .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStuName)
                                    .addComponent(txtStuID)
                                    .addComponent(txtDOB)
                                    .addComponent(txtBatch)
                                    .addComponent(jspAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(canvasProfImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        pnlStuPersonalInfoLayout.setVerticalGroup(
            pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStuInfoHeading)
                .addGap(18, 18, 18)
                .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStuID)
                            .addComponent(txtStuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStuName)
                            .addComponent(txtStuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDOB)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBatch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress)
                            .addComponent(jspAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(canvasProfImage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDNo)
                    .addComponent(tctIDno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone)
                    .addGroup(pnlStuPersonalInfoLayout.createSequentialGroup()
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDOReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDOReg))))
                .addGap(18, 18, 18)
                .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuardName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuardName))
                .addGap(18, 18, 18)
                .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGuardPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuardPhone))
                .addGap(18, 18, 18)
                .addGroup(pnlStuPersonalInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHostel)
                    .addComponent(chkHostel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStudSpecial.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlStudSpeInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnDailyAttendance.setText("View Daily Attendance");
        btnDailyAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDailyAttendanceActionPerformed(evt);
            }
        });

        btnSubAttendance.setText("View Subject Attendance");
        btnSubAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubAttendanceActionPerformed(evt);
            }
        });

        btnSubMarks.setText("View Subject Marks");
        btnSubMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubMarksActionPerformed(evt);
            }
        });

        btnPrintCV.setText("Print Character Certificate");

        lblCurricular.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCurricular.setText("Curricular Information");

        javax.swing.GroupLayout pnlStudSpeInfoLayout = new javax.swing.GroupLayout(pnlStudSpeInfo);
        pnlStudSpeInfo.setLayout(pnlStudSpeInfoLayout);
        pnlStudSpeInfoLayout.setHorizontalGroup(
            pnlStudSpeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudSpeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudSpeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDailyAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSubMarks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrintCV, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudSpeInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCurricular)
                .addGap(43, 43, 43))
        );
        pnlStudSpeInfoLayout.setVerticalGroup(
            pnlStudSpeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudSpeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurricular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDailyAttendance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubAttendance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubMarks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrintCV)
                .addContainerGap())
        );

        pnlStuDbControls.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPrevRecord.setText("Previous");
        btnPrevRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevRecordActionPerformed(evt);
            }
        });

        btnNextRecord.setText("Next");
        btnNextRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextRecordActionPerformed(evt);
            }
        });

        lblStuDbControls.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStuDbControls.setText("Student Database Controls");

        btnEditInfo.setText("Edit Information");
        btnEditInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInfoActionPerformed(evt);
            }
        });

        btnDeleteRecord.setText("Delete");

        javax.swing.GroupLayout pnlStuDbControlsLayout = new javax.swing.GroupLayout(pnlStuDbControls);
        pnlStuDbControls.setLayout(pnlStuDbControlsLayout);
        pnlStuDbControlsLayout.setHorizontalGroup(
            pnlStuDbControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuDbControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStuDbControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrevRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStuDbControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeleteRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(btnNextRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlStuDbControlsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblStuDbControls)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlStuDbControlsLayout.setVerticalGroup(
            pnlStuDbControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuDbControlsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblStuDbControls)
                .addGap(18, 18, 18)
                .addGroup(pnlStuDbControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevRecord)
                    .addComponent(btnNextRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStuDbControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditInfo)
                    .addComponent(btnDeleteRecord))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pnlStudSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblSearchStudent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSearchStudent.setText("Search Student");

        lblStudentID.setText("Student ID");

        lblStudentName.setText("Student Name");

        btnSearchbyID.setText("Search");

        btnSearchbyName.setText("Search");

        javax.swing.GroupLayout pnlStudSearchLayout = new javax.swing.GroupLayout(pnlStudSearch);
        pnlStudSearch.setLayout(pnlStudSearchLayout);
        pnlStudSearchLayout.setHorizontalGroup(
            pnlStudSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudSearchLayout.createSequentialGroup()
                .addGroup(pnlStudSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudSearchLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearchbyName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudSearchLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlStudSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudSearchLayout.createSequentialGroup()
                                .addComponent(lblStudentID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudSearchLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSearchbyID))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudSearchLayout.createSequentialGroup()
                                .addComponent(lblStudentName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStudSearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSearchStudent)
                .addGap(80, 80, 80))
        );
        pnlStudSearchLayout.setVerticalGroup(
            pnlStudSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSearchStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchbyID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStudSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchbyName)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlStudSpecialLayout = new javax.swing.GroupLayout(pnlStudSpecial);
        pnlStudSpecial.setLayout(pnlStudSpecialLayout);
        pnlStudSpecialLayout.setHorizontalGroup(
            pnlStudSpecialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudSpecialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStudSpecialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStudSpeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStuDbControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStudSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlStudSpecialLayout.setVerticalGroup(
            pnlStudSpecialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStudSpecialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStudSpeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStuDbControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStudSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlStuInfoLayout = new javax.swing.GroupLayout(pnlStuInfo);
        pnlStuInfo.setLayout(pnlStuInfoLayout);
        pnlStuInfoLayout.setHorizontalGroup(
            pnlStuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStuPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlStudSpecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlStuInfoLayout.setVerticalGroup(
            pnlStuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStuPersonalInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStudSpecial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlsubMain.add(pnlStuInfo, "card2");

        pnlsubLecturerInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblLecturerInfo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblLecturerInfo.setText("Lecturer Information");

        lblLecturerID.setText("Lecturer ID");

        lblLecturerName.setText("Lecturer Name");

        lblNIC.setText("NIC");

        jLabel1.setText("Address");

        jLabel2.setText("Subjects");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        canvas1.setBackground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblLecturerID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLecturerName)
                            .addComponent(lblNIC)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLecturerID)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLecturerName)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNIC)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlsubLecturerInfoLayout = new javax.swing.GroupLayout(pnlsubLecturerInfo);
        pnlsubLecturerInfo.setLayout(pnlsubLecturerInfoLayout);
        pnlsubLecturerInfoLayout.setHorizontalGroup(
            pnlsubLecturerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsubLecturerInfoLayout.createSequentialGroup()
                .addGroup(pnlsubLecturerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlsubLecturerInfoLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblLecturerInfo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlsubLecturerInfoLayout.setVerticalGroup(
            pnlsubLecturerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsubLecturerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLecturerInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlStuDbControls1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPrevRecord1.setText("Previous");
        btnPrevRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevRecord1ActionPerformed(evt);
            }
        });

        btnNextRecord1.setText("Next");
        btnNextRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextRecord1ActionPerformed(evt);
            }
        });

        lblStuDbControls1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStuDbControls1.setText("Lecturer Database Controls");

        btnEditInfo1.setText("Edit Information");
        btnEditInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInfo1ActionPerformed(evt);
            }
        });

        btnDeleteRecord1.setText("Delete");

        javax.swing.GroupLayout pnlStuDbControls1Layout = new javax.swing.GroupLayout(pnlStuDbControls1);
        pnlStuDbControls1.setLayout(pnlStuDbControls1Layout);
        pnlStuDbControls1Layout.setHorizontalGroup(
            pnlStuDbControls1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuDbControls1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStuDbControls1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrevRecord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlStuDbControls1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteRecord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNextRecord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStuDbControls1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(lblStuDbControls1)
                .addGap(34, 34, 34))
        );
        pnlStuDbControls1Layout.setVerticalGroup(
            pnlStuDbControls1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStuDbControls1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblStuDbControls1)
                .addGap(18, 18, 18)
                .addGroup(pnlStuDbControls1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevRecord1)
                    .addComponent(btnNextRecord1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStuDbControls1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditInfo1)
                    .addComponent(btnDeleteRecord1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStuDbControls1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlStuDbControls1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLectInfoLayout = new javax.swing.GroupLayout(pnlLectInfo);
        pnlLectInfo.setLayout(pnlLectInfoLayout);
        pnlLectInfoLayout.setHorizontalGroup(
            pnlLectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLectInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlsubLecturerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLectInfoLayout.setVerticalGroup(
            pnlLectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLectInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlsubLecturerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlsubMain.add(pnlLectInfo, "card3");

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "StudentID", "Level", "Warning", "Probation"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 0, 0));
        jLabel9.setText("Repeat Warnings");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "StudentID", "Level", "Warning", "Probation"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setText("New Warnings");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 0));
        jLabel11.setText("Warnings");

        jButton1.setText("Print Warning List");

        jButton2.setText("Clear Notifications");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel10))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout pnlRepeatWarningsLayout = new javax.swing.GroupLayout(pnlRepeatWarnings);
        pnlRepeatWarnings.setLayout(pnlRepeatWarningsLayout);
        pnlRepeatWarningsLayout.setHorizontalGroup(
            pnlRepeatWarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRepeatWarningsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        pnlRepeatWarningsLayout.setVerticalGroup(
            pnlRepeatWarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRepeatWarningsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );

        pnlsubMain.add(pnlRepeatWarnings, "card4");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Subject Information");

        jLabel4.setText("Subject");

        txtNoOFLectures.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtNoOFLectures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoOFLecturesActionPerformed(evt);
            }
        });

        jLabel5.setText("No Of Lectures");

        jLabel6.setText("Lecturers");

        cmbLecturers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lecturer 1", "Lecturer 2", "Lecturer 3" }));

        cmbSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Subject", "Subject 1", "Subject 2", "Subject 3" }));

        jLabel7.setText("Level");

        cmbLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Subject", "Level 1", "Level 2", "Level 3" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNoOFLectures, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cmbSubject, javax.swing.GroupLayout.Alignment.TRAILING, 0, 276, Short.MAX_VALUE)
                                .addComponent(cmbLevel, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3)))
                .addContainerGap(586, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNoOFLectures, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(613, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSubjectInformationLayout = new javax.swing.GroupLayout(pnlSubjectInformation);
        pnlSubjectInformation.setLayout(pnlSubjectInformationLayout);
        pnlSubjectInformationLayout.setHorizontalGroup(
            pnlSubjectInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubjectInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSubjectInformationLayout.setVerticalGroup(
            pnlSubjectInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubjectInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlsubMain.add(pnlSubjectInformation, "card5");

        pnlsubOverallDailyAttendance.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbldate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldate.setText("Date");

        cmbyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027" }));
        cmbyear.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cmbMonth.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmbDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day" }));
        cmbDay.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Index", "Name", "Status", "Leave"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        lbldate1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldate1.setText("Level");

        cmbyear1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "1", "2", "3" }));
        cmbyear1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Daily Attendance");

        javax.swing.GroupLayout pnlsubOverallDailyAttendanceLayout = new javax.swing.GroupLayout(pnlsubOverallDailyAttendance);
        pnlsubOverallDailyAttendance.setLayout(pnlsubOverallDailyAttendanceLayout);
        pnlsubOverallDailyAttendanceLayout.setHorizontalGroup(
            pnlsubOverallDailyAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsubOverallDailyAttendanceLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addGap(95, 95, 95)
                .addGroup(pnlsubOverallDailyAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldate1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlsubOverallDailyAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbyear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
            .addGroup(pnlsubOverallDailyAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pnlsubOverallDailyAttendanceLayout.setVerticalGroup(
            pnlsubOverallDailyAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsubOverallDailyAttendanceLayout.createSequentialGroup()
                .addGroup(pnlsubOverallDailyAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlsubOverallDailyAttendanceLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnlsubOverallDailyAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldate)
                            .addComponent(cmbyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlsubOverallDailyAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldate1)
                            .addComponent(cmbyear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlsubOverallDailyAttendanceLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlOverallDailyAttendanceLayout = new javax.swing.GroupLayout(pnlOverallDailyAttendance);
        pnlOverallDailyAttendance.setLayout(pnlOverallDailyAttendanceLayout);
        pnlOverallDailyAttendanceLayout.setHorizontalGroup(
            pnlOverallDailyAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOverallDailyAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlsubOverallDailyAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOverallDailyAttendanceLayout.setVerticalGroup(
            pnlOverallDailyAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOverallDailyAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlsubOverallDailyAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlsubMain.add(pnlOverallDailyAttendance, "card6");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlsubMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlsubMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuInfoActionPerformed
       layCard.show(pnlsubMain,"pnlStuInfo" );
    }//GEN-LAST:event_btnStuInfoActionPerformed

    private void btnSubjInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjInfoActionPerformed
        layCard.show(pnlsubMain,"pnlSubjectInfo");
    }//GEN-LAST:event_btnSubjInfoActionPerformed

    private void btnNextRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextRecordActionPerformed
        
    }//GEN-LAST:event_btnNextRecordActionPerformed

    private void btnPrevRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevRecordActionPerformed

    private void chkHostelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHostelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkHostelActionPerformed

    private void txtGuardNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardNameActionPerformed

    private void txtDORegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDORegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDORegActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnLectInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLectInfoActionPerformed
        layCard.show(pnlsubMain, "pnlLectInfo");
    }//GEN-LAST:event_btnLectInfoActionPerformed

    private void btnRepeatWarnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepeatWarnActionPerformed
        layCard.show(pnlsubMain, "pnlRepeatWarnings");
    }//GEN-LAST:event_btnRepeatWarnActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void btnEditInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInfoActionPerformed
        new EditStudentInformation().show();
    }//GEN-LAST:event_btnEditInfoActionPerformed

    private void btnPrevRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevRecord1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevRecord1ActionPerformed

    private void btnNextRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextRecord1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextRecord1ActionPerformed

    private void btnEditInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInfo1ActionPerformed
        EditLecturerInformation editLecturerInformation = new EditLecturerInformation();
        editLecturerInformation.setVisible(true);
    }//GEN-LAST:event_btnEditInfo1ActionPerformed

    private void btnSubMarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubMarksActionPerformed
        SubjectMarks subjectMarks = new SubjectMarks();
        subjectMarks.setVisible(true);
    }//GEN-LAST:event_btnSubMarksActionPerformed

    private void btnOverallDailyAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverallDailyAttendanceActionPerformed
        layCard.show(pnlsubMain, "pnlODA");
    }//GEN-LAST:event_btnOverallDailyAttendanceActionPerformed

    private void btnDailyAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDailyAttendanceActionPerformed
        DailyAttendance dailyAttendance = new DailyAttendance();
        dailyAttendance.setVisible(true);
    }//GEN-LAST:event_btnDailyAttendanceActionPerformed

    private void btnSubAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubAttendanceActionPerformed
        SubjectAttendance subjectAttendance = new SubjectAttendance();
        subjectAttendance.setVisible(true);
    }//GEN-LAST:event_btnSubAttendanceActionPerformed

    private void btnUpdateRepWarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRepWarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateRepWarActionPerformed

    private void txtNoOFLecturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoOFLecturesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoOFLecturesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
                    //UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDailyAttendance;
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnDeleteRecord1;
    private javax.swing.JButton btnEditInfo;
    private javax.swing.JButton btnEditInfo1;
    private javax.swing.JButton btnLectInfo;
    private javax.swing.JButton btnNextRecord;
    private javax.swing.JButton btnNextRecord1;
    private javax.swing.JButton btnOverallDailyAttendance;
    private javax.swing.JButton btnPrevRecord;
    private javax.swing.JButton btnPrevRecord1;
    private javax.swing.JButton btnPrintCV;
    private javax.swing.JButton btnRepeatWarn;
    private javax.swing.JButton btnSearchbyID;
    private javax.swing.JButton btnSearchbyName;
    private javax.swing.JButton btnStuInfo;
    private javax.swing.JButton btnSubAttendance;
    private javax.swing.JButton btnSubMarks;
    private javax.swing.JButton btnSubjInfo;
    private javax.swing.JButton btnUpdateRepWar;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvasProfImage;
    private javax.swing.JCheckBox chkHostel;
    private javax.swing.JComboBox cmbDay;
    private javax.swing.JComboBox cmbLecturers;
    private javax.swing.JComboBox cmbLevel;
    private javax.swing.JComboBox cmbMonth;
    private javax.swing.JComboBox cmbSubject;
    private javax.swing.JComboBox cmbyear;
    private javax.swing.JComboBox cmbyear1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JScrollPane jspAddress;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblCurricular;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOReg;
    private javax.swing.JLabel lblGuardName;
    private javax.swing.JLabel lblGuardPhone;
    private javax.swing.JLabel lblHostel;
    private javax.swing.JLabel lblIDNo;
    private javax.swing.JLabel lblLastChkDate;
    private javax.swing.JLabel lblLastchk;
    private javax.swing.JLabel lblLecturerID;
    private javax.swing.JLabel lblLecturerInfo;
    private javax.swing.JLabel lblLecturerName;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JLabel lblSearchStudent;
    private javax.swing.JLabel lblStuDbControls;
    private javax.swing.JLabel lblStuDbControls1;
    private javax.swing.JLabel lblStuID;
    private javax.swing.JLabel lblStuInfoHeading;
    private javax.swing.JLabel lblStuName;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lbldate1;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlLectInfo;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlOverallDailyAttendance;
    private javax.swing.JPanel pnlRepeatWarnings;
    private javax.swing.JPanel pnlSideBar;
    private javax.swing.JPanel pnlStuDbControls;
    private javax.swing.JPanel pnlStuDbControls1;
    private javax.swing.JPanel pnlStuInfo;
    private javax.swing.JPanel pnlStuPersonalInfo;
    private javax.swing.JPanel pnlStudSearch;
    private javax.swing.JPanel pnlStudSpeInfo;
    private javax.swing.JPanel pnlStudSpecial;
    private javax.swing.JPanel pnlSubjectInformation;
    private javax.swing.JPanel pnlsubLecturerInfo;
    private javax.swing.JPanel pnlsubMain;
    private javax.swing.JPanel pnlsubOverallDailyAttendance;
    private javax.swing.JTextField tctIDno;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBatch;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDOReg;
    private javax.swing.JTextField txtGuardName;
    private javax.swing.JTextField txtGuardPhone;
    private javax.swing.JTextField txtNoOFLectures;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtStuID;
    private javax.swing.JTextField txtStuName;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
